name: build
run-name: ${{ github.actor }} is building 🚀
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest

    steps:

      - name: checkout code
        uses: actions/checkout@v3

      - name: 📂 upload to aliyun
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: wh-ah48jjb7o8ffrmcbqon.my3w.com
          user: wh-ah48jjb7o8ffrmcbqon
          password: Ap20s32019
          localDir: ./src
          remoteDir: /htdocs